version: "3.3"
services:

    mysql:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: aqidb
            MYSQL_USER: pl3w #postgres
            MYSQL_PASSWORD: Pbw101031 #1234
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - /var/lib/docker/volumes/mysql/_data:/var/lib/mysql
        networks:
            - aqi_net

        


    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.1.0
        links:
            - mysql:db
        ports:
            - "8000:80"
        depends_on:
            - mysql
        networks:
            - aqi_net


networks:
  aqi_net:
    external: true


volumes:
  mysql:
    external: true
