version: "3.0"
services:
  scheduler:
    image: crawler:1.1.0
    hostname: "aqi"
    command: pipenv run python src/aqidata/scheduler.py
    environment:
      - TZ=Asia/Taipei
    deploy:
      mode: replicated
      replicas: 1
      placement: 
          constraints: [node.labels.crawler_scheduler == true]
    networks:
      - aqi_net

networks:
  aqi_net:
    external: true
